logstash:
  image: logstash:2.3
  command: logstash -f /etc/logstash/conf.d/ --allow-env --verbose
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  environment:
    ELASTICSEARCH_ENDPOINT: ${ELASTICSEARCH_ENDPOINT}
  ports:
    - "5000:5000"
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  environment:
    ELASTICSEARCH_ENDPOINT: ${ELASTICSEARCH_ENDPOINT}
